/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StockPick = IDL.Record({
  'urgencyLevel' : IDL.Text,
  'sentimentScore' : IDL.Nat,
  'revenueBeatPct' : IDL.Int,
  'analystCoverageScore' : IDL.Text,
  'riskFactors' : IDL.Text,
  'triggerSummary' : IDL.Text,
  'sourceCount' : IDL.Nat,
  'confidenceScore' : IDL.Nat,
  'volumeSpikeMultiplier' : IDL.Int,
  'aiExplanation' : IDL.Text,
  'timestamp' : IDL.Int,
  'priceChangePct' : IDL.Int,
  'marketCapCategory' : IDL.Text,
  'companyName' : IDL.Text,
  'whyItMayMoveMore' : IDL.Text,
  'symbol' : IDL.Text,
  'profitBeatPct' : IDL.Int,
  'eventType' : IDL.Text,
});
export const BreakingNewsTrade = IDL.Record({
  'id' : IDL.Text,
  'urgencyScore' : IDL.Nat,
  'headline' : IDL.Text,
  'confidenceLevel' : IDL.Text,
  'timestamp' : IDL.Int,
  'companyName' : IDL.Text,
  'sources' : IDL.Vec(IDL.Text),
  'companySymbol' : IDL.Text,
  'keywordMatched' : IDL.Text,
  'eventType' : IDL.Text,
});
export const ScanMetadata = IDL.Record({
  'totalPicksGenerated' : IDL.Nat,
  'marketStatus' : IDL.Text,
  'dataFreshnessMinutes' : IDL.Nat,
  'nextScheduledScan' : IDL.Int,
  'lastScanTimestamp' : IDL.Int,
  'scanStatus' : IDL.Text,
  'totalBreakingNews' : IDL.Nat,
});

export const idlService = IDL.Service({
  'clearAllData' : IDL.Func([], [], []),
  'getAllPicks' : IDL.Func([], [IDL.Vec(StockPick)], ['query']),
  'getBreakingNewsTrades' : IDL.Func(
      [],
      [IDL.Vec(BreakingNewsTrade)],
      ['query'],
    ),
  'getScanMetadata' : IDL.Func([], [ScanMetadata], ['query']),
  'getTopPicks' : IDL.Func([], [IDL.Vec(StockPick)], ['query']),
  'triggerManualScan' : IDL.Func([], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StockPick = IDL.Record({
    'urgencyLevel' : IDL.Text,
    'sentimentScore' : IDL.Nat,
    'revenueBeatPct' : IDL.Int,
    'analystCoverageScore' : IDL.Text,
    'riskFactors' : IDL.Text,
    'triggerSummary' : IDL.Text,
    'sourceCount' : IDL.Nat,
    'confidenceScore' : IDL.Nat,
    'volumeSpikeMultiplier' : IDL.Int,
    'aiExplanation' : IDL.Text,
    'timestamp' : IDL.Int,
    'priceChangePct' : IDL.Int,
    'marketCapCategory' : IDL.Text,
    'companyName' : IDL.Text,
    'whyItMayMoveMore' : IDL.Text,
    'symbol' : IDL.Text,
    'profitBeatPct' : IDL.Int,
    'eventType' : IDL.Text,
  });
  const BreakingNewsTrade = IDL.Record({
    'id' : IDL.Text,
    'urgencyScore' : IDL.Nat,
    'headline' : IDL.Text,
    'confidenceLevel' : IDL.Text,
    'timestamp' : IDL.Int,
    'companyName' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
    'companySymbol' : IDL.Text,
    'keywordMatched' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const ScanMetadata = IDL.Record({
    'totalPicksGenerated' : IDL.Nat,
    'marketStatus' : IDL.Text,
    'dataFreshnessMinutes' : IDL.Nat,
    'nextScheduledScan' : IDL.Int,
    'lastScanTimestamp' : IDL.Int,
    'scanStatus' : IDL.Text,
    'totalBreakingNews' : IDL.Nat,
  });
  
  return IDL.Service({
    'clearAllData' : IDL.Func([], [], []),
    'getAllPicks' : IDL.Func([], [IDL.Vec(StockPick)], ['query']),
    'getBreakingNewsTrades' : IDL.Func(
        [],
        [IDL.Vec(BreakingNewsTrade)],
        ['query'],
      ),
    'getScanMetadata' : IDL.Func([], [ScanMetadata], ['query']),
    'getTopPicks' : IDL.Func([], [IDL.Vec(StockPick)], ['query']),
    'triggerManualScan' : IDL.Func([], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };