/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BreakingNewsTrade {
  'id' : string,
  'urgencyScore' : bigint,
  'headline' : string,
  'confidenceLevel' : string,
  'timestamp' : bigint,
  'companyName' : string,
  'sources' : Array<string>,
  'companySymbol' : string,
  'keywordMatched' : string,
  'eventType' : string,
}
export interface ScanMetadata {
  'totalPicksGenerated' : bigint,
  'marketStatus' : string,
  'dataFreshnessMinutes' : bigint,
  'nextScheduledScan' : bigint,
  'lastScanTimestamp' : bigint,
  'scanStatus' : string,
  'totalBreakingNews' : bigint,
}
export interface StockPick {
  'urgencyLevel' : string,
  'sentimentScore' : bigint,
  'revenueBeatPct' : bigint,
  'analystCoverageScore' : string,
  'riskFactors' : string,
  'triggerSummary' : string,
  'sourceCount' : bigint,
  'confidenceScore' : bigint,
  'volumeSpikeMultiplier' : bigint,
  'aiExplanation' : string,
  'timestamp' : bigint,
  'priceChangePct' : bigint,
  'marketCapCategory' : string,
  'companyName' : string,
  'whyItMayMoveMore' : string,
  'symbol' : string,
  'profitBeatPct' : bigint,
  'eventType' : string,
}
export interface _SERVICE {
  'clearAllData' : ActorMethod<[], undefined>,
  'getAllPicks' : ActorMethod<[], Array<StockPick>>,
  'getBreakingNewsTrades' : ActorMethod<[], Array<BreakingNewsTrade>>,
  'getScanMetadata' : ActorMethod<[], ScanMetadata>,
  'getTopPicks' : ActorMethod<[], Array<StockPick>>,
  'triggerManualScan' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];